FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY app/ ./app/
COPY run_mcp.py .
COPY run_mcp_internal.py .
COPY wechatpay_private_key.pem ./wechatpay_private_key.pem
COPY wechatpay_public_key.pem ./wechatpay_public_key.pem

EXPOSE 8000

CMD ["python", "run_mcp.py"]